USE [GSSWEB]
GO

SELECT blr.KEEPER_ID,mm.USER_CNAME AS CName, mm.USER_ENAME AS EName, Year(blr.LEND_DATE)  AS BorrowYear, COUNT( YEAR(mm.CREATE_DATE)) AS BorrowCnt
FROM MEMBER_M mm JOIN BOOK_LEND_RECORD blr ON mm.USER_ID = blr.KEEPER_ID
GROUP BY blr.KEEPER_ID, mm.USER_CNAME, mm.USER_ENAME,year(blr.LEND_DATE)
ORDER BY blr.KEEPER_ID

SELECT TOP 5 blr.BOOK_ID AS BookID, bd.BOOK_NAME AS BookName, COUNT(blr.BOOK_ID) AS QTY
FROM BOOK_LEND_RECORD blr JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID
GROUP BY blr.BOOK_ID, bd.BOOK_NAME
ORDER BY QTY DESC


SELECT CASE  (FORMAT(blr.LEND_DATE,'MM')-1)/3 
WHEN 0  THEN '2019/01~2019/03'
WHEN 1  THEN '2019/04~2019/06'
WHEN 2  THEN '2019/07~2019/09'
WHEN 3  THEN '2019/10~2019/12'
END [quarter] 
,COUNT( (FORMAT(blr.LEND_DATE,'MM')-1)/3 ) AS Cnt
FROM BOOK_LEND_RECORD blr
GROUP BY (FORMAT(blr.LEND_DATE,'MM')-1)/3 ,FORMAT(blr.LEND_DATE,'yyyy')
HAVING FORMAT(blr.LEND_DATE,'yyyy')>2018

SELECT * FROM BOOK_LEND_RECORD blr
SELECT * FROM BOOK_CLASS bc
SELECT * FROM BOOK_DATA bd
CREATE SEQUENCE num INCREMENT BY 1 START WITH 1 MAXVALUE 3 CYCLE NO CACHE

SELECT TOP 3 bc.BOOK_CLASS_NAME AS BookClass, blr.BOOK_ID AS BookId, bd.BOOK_NAME AS BookName, COUNT(blr.BOOK_ID) AS Cnt
FROM BOOK_LEND_RECORD blr JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
GROUP BY bc.BOOK_CLASS_NAME, blr.BOOK_ID, bd.BOOK_NAME

