USE [GSSWEB]
GO

/*1*/
SELECT blr.KEEPER_ID,mm.USER_CNAME AS CName, mm.USER_ENAME AS EName, Year(blr.LEND_DATE)  AS BorrowYear, COUNT( YEAR(mm.CREATE_DATE)) AS BorrowCnt
FROM MEMBER_M mm JOIN BOOK_LEND_RECORD blr ON mm.USER_ID = blr.KEEPER_ID
GROUP BY blr.KEEPER_ID, mm.USER_CNAME, mm.USER_ENAME,year(blr.LEND_DATE)
ORDER BY blr.KEEPER_ID

/*2*/
SELECT TOP 5 blr.BOOK_ID AS BookID, bd.BOOK_NAME AS BookName, COUNT(blr.BOOK_ID) AS QTY
FROM BOOK_LEND_RECORD blr JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID
GROUP BY blr.BOOK_ID, bd.BOOK_NAME
ORDER BY QTY DESC

/*3*/
SELECT CASE  (FORMAT(blr.LEND_DATE,'MM')-1)/3 
		WHEN 0  THEN '2019/01~2019/03'
		WHEN 1  THEN '2019/04~2019/06'
		WHEN 2  THEN '2019/07~2019/09'
		WHEN 3  THEN '2019/10~2019/12'
		END [quarter] ,COUNT( (FORMAT(blr.LEND_DATE,'MM')-1)/3 ) AS Cnt
FROM BOOK_LEND_RECORD blr
GROUP BY (FORMAT(blr.LEND_DATE,'MM')-1)/3 ,FORMAT(blr.LEND_DATE,'yyyy')
HAVING FORMAT(blr.LEND_DATE,'yyyy')>2018

/*4*/
SELECT Seq,BookClass, BookId, BookName, Cnt 
FROM 
		(SELECT ROW_NUMBER() OVER(PARTITION BY bc.BOOK_CLASS_NAME ORDER BY COUNT(blr.BOOK_ID) DESC) AS Seq,
		bc.BOOK_CLASS_NAME AS BookClass,blr.BOOK_ID AS BookId,bd.BOOK_NAME AS BookName,COUNT(blr.BOOK_ID) AS Cnt 
		FROM BOOK_LEND_RECORD blr 
		JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID
		JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
		GROUP BY bc.BOOK_CLASS_NAME,blr.BOOK_ID,bd.BOOK_NAME) AS Sub
WHERE Sub.Seq<4
GROUP BY Seq,BookClass, BookId, BookName, Cnt 

/*5*/
SELECT  ClassID, ClassName,
SUM(CASE Sub.year WHEN 2016 THEN Sub.CNT ELSE 0 END) AS CTN2016,
SUM(CASE Sub.year WHEN 2017 THEN Sub.CNT ELSE 0 END) AS CTN2017,
SUM(CASE Sub.year WHEN 2018 THEN Sub.CNT ELSE 0 END) AS CTN2018,
SUM(CASE Sub.year WHEN 2019 THEN Sub.CNT ELSE 0 END) AS CTN2019
FROM
	(SELECT bc.BOOK_CLASS_ID AS ClassID, bc.BOOK_CLASS_NAME AS ClassName,YEAR(blr.LEND_DATE) AS [year], COUNT(blr.BOOK_ID) AS CNT
	 FROM BOOK_LEND_RECORD blr JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	 GROUP BY bc.BOOK_CLASS_ID, bc.BOOK_CLASS_NAME,YEAR(blr.LEND_DATE))AS Sub
GROUP BY ClassID, ClassName
ORDER BY ClassID

/*6*/
SELECT  ClassID, ClassName,ISNULL([2016],0) AS CTN2016,ISNULL([2017],0) AS CTN2017,ISNULL([2018],0) AS CTN2018,ISNULL([2019],0) AS CTN2019
FROM 
	 (SELECT bc.BOOK_CLASS_ID AS ClassID, bc.BOOK_CLASS_NAME AS ClassName,YEAR(blr.LEND_DATE) AS [year], COUNT(blr.BOOK_ID) AS CNT
	  FROM BOOK_LEND_RECORD blr JOIN BOOK_DATA bd ON blr.BOOK_ID = bd.BOOK_ID JOIN BOOK_CLASS bc ON bd.BOOK_CLASS_ID = bc.BOOK_CLASS_ID
	  GROUP BY bc.BOOK_CLASS_ID, bc.BOOK_CLASS_NAME,YEAR(blr.LEND_DATE))AS Sub
PIVOT (SUM(Sub.CNT) FOR Sub.year IN ([2016],[2017],[2018],[2019])) AS temp
ORDER BY ClassID

/*7*/
SELECT blr.BOOK_ID AS [書本ID],
	   FORMAT(bd.BOOK_BOUGHT_DATE,'yyyy/MM/dd') AS [購書日期],
	   FORMAT(blr.LEND_DATE,'yyyy/MM/dd') AS [借閱日期],
	   CONCAT(bc1.BOOK_CLASS_ID,'-',bc1.BOOK_CLASS_NAME) AS [書籍類別], 
	   CONCAT(blr.KEEPER_ID,'-',mm.USER_CNAME,'(',mm.USER_ENAME,')') AS [借閱人],
	   CONCAT(bd.BOOK_STATUS,'-',bc.CODE_NAME) AS [狀態],
	   CONCAT( CONVERT(NVARCHAR(20),CAST(bd.BOOK_AMOUNT AS Money),1),'元') AS [購書金額]
FROM BOOK_DATA bd 
JOIN BOOK_CODE bc ON bc.CODE_ID = bd.BOOK_STATUS 
JOIN BOOK_LEND_RECORD blr ON bd.BOOK_ID = blr.BOOK_ID
JOIN MEMBER_M mm ON blr.KEEPER_ID = mm.USER_ID
JOIN BOOK_CLASS bc1 ON bc1.BOOK_CLASS_ID = bd.BOOK_CLASS_ID
WHERE mm.USER_CNAME = '李四' 
ORDER BY bd.BOOK_AMOUNT DESC

/*8*/
SELECT * FROM temp_book tb
INSERT INTO BOOK_LEND_RECORD (BOOK_ID,KEEPER_ID,LEND_DATE)VALUES(2004,'0002',CONVERT(DATETIME,'2019/01/02'))
UPDATE temp_book SET 借閱日期 = '2019/01/02'

/*9*/
DELETE FROM BOOK_LEND_RECORD WHERE BOOK_ID = 2004

DROP TABLE temp_book
